# Análisis y visualización de datos de Tokyo_Airbnb

<img src="https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg" style= "height:150px;float:left;">

In [5]:
# Llamando librerias
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#import geopandas as gpd
import plotly.express as px
from IPython.display import HTML
import plotly.io as pio

In [6]:
#leer datos
datos = pd.read_csv('tokyo_airbnb.csv')

In [ ]:
# Exploración básica del dataset

In [7]:
datos

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month
0,35303,"La Casa Gaienmae C Harajuku, Omotesando is nearby",151977,Miyuki,NaN,Shibuya Ku,35.67152,139.71203,Private room,4196,28,18,2018-07-28,0.20
1,197677,Oshiage Holiday Apartment,964081,Yoshimi & Marek,NaN,Sumida Ku,35.71721,139.82596,Entire home/apt,10975,3,156,2019-05-21,1.65
2,289597,Private apt in central Tokyo #203,341577,Hide&Kei,NaN,Nerima Ku,35.74267,139.65810,Entire home/apt,4196,30,107,2019-05-25,1.25
3,370759,"Cozy flat #203, local area YET 10 mins to shib...",1573631,"Gilles,Mayumi,Taiki",NaN,Setagaya Ku,35.66344,139.65593,Entire home/apt,6994,29,99,2019-05-07,1.55
4,700253,Private apt in central Tokyo #201,341577,Hide&Kei,NaN,Nerima Ku,35.74264,139.65832,Entire home/apt,3981,30,101,2019-05-03,1.24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11461,36083287,1min to station · Skytree/Tatami hotel/new design,235406925,Sayoko佐代子,NaN,Sumida Ku,35.70862,139.81393,Entire home/apt,21951,1,0,NaN,NaN
11462,36083512,Asakusa Wired house 5pax near by UENO/AKIHABARA,267481408,Hyongsu,NaN,Taito Ku,35.72464,139.78078,Entire home/apt,7747,1,0,NaN,NaN
11463,36084566,东京精品民宿,161702799,Yang,NaN,Toshima Ku,35.73587,139.73397,Private room,56275,1,0,NaN,NaN
11464,36085357,#4 DIRECT ACCESS TO DISNEY IN BUS! 3MIN TO STA...,208189463,Shotaro,NaN,Edogawa Ku,35.66255,139.87236,Entire home/apt,6456,1,0,NaN,NaN
11465,36086604,103号室:立地最高!駅近･買い物便利!改装したばかりの綺麗な和室です｡,254667806,新東明,NaN,Shinjuku Ku,35.69889,139.70544,Private room,7962,2,0,NaN,NaN

In [8]:
# Descripción de características
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11466 entries, 0 to 11465
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   11466 non-null  int64
 1   name                 11466 non-null  object
 2   host_id              11466 non-null  int64
 3   host_name            11450 non-null  object
 4   neighbourhood_group  0 non-null      float64
 5   neighbourhood        11466 non-null  object
 6   latitude             11466 non-null  float64
 7   longitude            11466 non-null  float64
 8   room_type            11466 non-null  object
 9   price                11466 non-null  int64
 10  minimum_nights       11466 non-null  int64
 11  number_of_reviews    11466 non-null  int64
 12  last_review          9789 non-null   object
 13  reviews_per_month    9789 non-null   float64
dtypes: float64(4), int64(5), object(5)
memory usage: 1.2+ MB

In [ ]:
# Comentario sobre el dataset:
# 1.Hay 14 columnas de características en total, cada una con 11466 datos.
# 2.Las 4 columnas con datos faltantes:
# 3   host_name            11450 non-null  object 
# 4   neighbourhood_group  0 non-null      float64
# 12  last_review          9789 non-null   object 
# 13  reviews_per_month    9789 non-null   float64